openapi: 3.0.1
info:
  title: QuerySuccessfulResults
  description: QuerySuccessfulResults
  version: 1.0.0
servers:
  - url: http://localhost:8290/salesforce/createquery
paths:
  /:
    post:
      requestBody:
        
        content:
          application/json:
            schema:
              type: object
            
      responses:
        default:
          description: Default response
          content:
            application/json:
              
